name: Portrait
favicon: null
layout_spectrum: 0.25282
typography_spectrum: 0.51856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6a6a6a'
    - '#8c8c8c'
    - '#303030'
  brandStrength: 0.9742637323215604
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
