name: Portrait
favicon: null
layout_spectrum: 0.5117008439265192
typography_spectrum: 0.21392231085337698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9742637323215604
  lightness: 0.6837941207922995
  saturation: 0.20495039084926248
  rhythmicContrast: 0.07383307977579534
purpose: []
